version: "3"

services:

  redis:
    image: redis:alpine
    ports:
      - 6379

  mafia-bot:
    depends_on:
      - redis
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_HOST=redis
      - LOCALE_LANG_COUNTRY=${LOCALE_LANG_COUNTRY}
      - ZEUS_ID=${ZEUS_ID}
